Fix yaml whitespace

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -75,15 +75,15 @@ jobs:
       - uses: actions-rust-lang/setup-rust-toolchain@v1.8
       - run: cargo build --bin smp --release
       - run: |
-        for config in ./examples/*.yaml; do
-          echo "Testing with config $config"
-          timeout 1 ./target/release/lading --no-target --config-path "$config"
-          exit_code=$?
-          if [ $exit_code -ne 124 ]; then
-            echo "Test failed or did not timeout for $config"
-            exit 1
-          fi
-        done
+          for config in ./examples/*.yaml; do
+            echo "Testing with config $config"
+            timeout 1 ./target/release/lading --no-target --config-path "$config"
+            exit_code=$?
+            if [ $exit_code -ne 124 ]; then
+              echo "Test failed or did not timeout for $config"
+              exit 1
+            fi
+          done
 
   kani:
     name: Kani Proofs
